package com.bracits.hrms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedbackDetailsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackDetailsAllPropertiesEquals(FeedbackDetails expected, FeedbackDetails actual) {
        assertFeedbackDetailsAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedbackDetailsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackDetailsAllUpdatablePropertiesEquals(FeedbackDetails expected, FeedbackDetails actual) {
        assertFeedbackDetailsUpdatableFieldsEquals(expected, actual);
        assertFeedbackDetailsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackDetailsAutoGeneratedPropertiesEquals(FeedbackDetails expected, FeedbackDetails actual) {
        assertThat(expected)
            .as("Verify FeedbackDetails auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackDetailsUpdatableFieldsEquals(FeedbackDetails expected, FeedbackDetails actual) {
        assertThat(expected)
            .as("Verify FeedbackDetails relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getCommentsforfeedbacksubtype())
                        .as("check commentsforfeedbacksubtype")
                        .isEqualTo(actual.getCommentsforfeedbacksubtype())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackDetailsUpdatableRelationshipsEquals(FeedbackDetails expected, FeedbackDetails actual) {
        assertThat(expected)
            .as("Verify FeedbackDetails relationships")
            .satisfies(e -> assertThat(e.getFeedbackdetails()).as("check feedbackdetails").isEqualTo(actual.getFeedbackdetails()))
            .satisfies(e -> assertThat(e.getFeedbacksubtypes()).as("check feedbacksubtypes").isEqualTo(actual.getFeedbacksubtypes()))
            .satisfies(e -> assertThat(e.getRatings()).as("check ratings").isEqualTo(actual.getRatings()));
    }
}
